"""Generate paper/numbers.tex from results/fractal/*.json. Every number in the paper comes from here.

Missing results produce '??' so the paper still builds and the gap is visible.

  run.cmd tools/fractal_numbers.py
"""

from __future__ import annotations

import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from fractal_analyze import pair_stats  # noqa: E402

R = os.path.join(ROOT, "results", "fractal")
M = {}


def J(name):
    p = os.path.join(R, name)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def f2(x, nd=2):
    return "??" if x is None else ("%.*f" % (nd, x))


def pct(x, nd=1):
    return "??" if x is None else ("%.*f\\%%" % (nd, 100 * x))


def pairs(tag, fname, prefix):
    d = J(fname)
    if d is None:
        for k in ("", "lo", "hi", "C", "floor", "flip", "n"):
            M[prefix + k] = "??"
        return None
    s = pair_stats(d)
    a, ci = s["alpha"], s["alpha_ci95"]
    M[prefix] = f2(a)
    M[prefix + "lo"] = f2(ci[0]) if ci else "??"
    M[prefix + "hi"] = f2(ci[1]) if ci else "??"
    M[prefix + "C"] = f2(2 ** (1 / a), 1) if a else "??"
    M[prefix + "floor"] = pct(s["p0"])
    row = [r for r in s["rows"] if abs(r["eps"] - 0.001) < 1e-12]
    M[prefix + "flip"] = pct(row[0]["f"]) if row else "??"
    M[prefix + "n"] = str(len(s["usable_eps"]))
    s["_raw"] = d
    return s


def main():
    g2 = pairs("G2", "pairs.json", "alphaG")
    pairs("pol", "pairs_T5orbit.json", "alphaPol")
    pairs("act", "P2_pairs.json", "alphaAct")
    pairs("z1", "pairs_zoom.json", "alphaZoomOne")
    pairs("z2", "pairs_zoomZ2.json", "alphaZoomTwo")
    cpu = pairs("cpu", "R1_cpu_pairs.json", "alphaCPU")
    ic = []
    for i, L in enumerate("abcde"):
        s = pairs("ic%d" % i, "R2_ic%d_pairs.json" % i, "alphaIC" + L)
        ic.append(s["alpha"] if s and s["alpha"] is not None else None)
    got = [a for a in ic if a is not None]
    M["alphaICmed"] = f2(float(np.median(got))) if got else "??"
    M["alphaICmin"] = f2(min(got)) if got else "??"
    M["alphaICmax"] = f2(max(got)) if got else "??"
    M["nICbelow"] = str(sum(a < 0.8 for a in got)) if got else "??"
    st = pairs("state", "R3_state_pairs.json", "alphaState")
    M["stateHalf"] = f2(st["_raw"]["window"]["half"], 2) if st else "??"
    pairs("fine", "R4_fine_pairs.json", "alphaFine")

    # mechanism check: IC0 through the per-environment IC table must reproduce G2 exactly
    ic0, gp = J("R2_ic0_pairs.json"), J("pairs.json")
    M["icMechanism"] = "??" if not (ic0 and gp) else ("identical" if ic0["success"] == gp["success"]
                                                     else "%.2f\\%% different" % (100 * np.mean(np.array(ic0["success"]) != np.array(gp["success"]))))
    # CPU vs Isaac outcome agreement on the same pairs
    if cpu and gp:
        M["agreeCPU"] = pct(float(np.mean(np.array(cpu["_raw"]["success"]) == np.array(gp["success"]))))
        M["succCPU"] = pct(float(np.mean(cpu["_raw"]["success"])))
    else:
        M["agreeCPU"] = M["succCPU"] = "??"

    ga = J("analysis_gate.json")
    if ga:
        M["succGrid"] = pct(ga["grid"]["success_frac"])
        M["bndGrid"] = pct(ga["grid"]["boundary_cell_frac"])
        M["dzero"] = pct(ga["grid"]["d0_within_run"])
        M["rzero"] = pct(ga["grid"].get("r0_run_to_run", 0.0))
    pg = J("analysis_P2grid.json")
    M["bndAct"] = pct(pg["grid"]["boundary_cell_frac"]) if pg else "??"
    se = J("analysis_small_EXPLORATORY.json")
    if se:
        rows = se["pairs"]["rows"]
        small = [r["f"] for r in rows if 0 < r["eps"] <= 3e-4]
        M["plateauLo"], M["plateauHi"] = pct(min(small)), pct(max(small))
        M["plateauFloor"] = pct(rows[0]["f"])
    fd = J("ftle_divergent_EXPLORATORY.json")
    if fd:
        lam = [v["growth_rate_1e-5_to_1e-1_per_s_median"] for v in fd.values() if v.get("growth_rate_1e-5_to_1e-1_per_s_median")]
        M["lamLo"], M["lamHi"] = f2(min(lam), 1), f2(max(lam), 1)
        M["divZero"] = pct(fd["0.0"]["frac_final_sep_gt_0.3"], 0)
        M["divMilli"] = pct(fd["0.001"]["frac_final_sep_gt_0.3"], 0)
        M["tReach"] = f2(fd["0.001"]["t_reach_0.1_median_s"], 1)
    cg = J("cartpole/grid.json")
    if cg:
        n = cg["meta"]["n"]
        C = np.array(cg["success"]).reshape(n, n)
        d = np.zeros_like(C)
        d[1:, :] += C[1:, :] != C[:-1, :]
        d[:-1, :] += C[:-1, :] != C[1:, :]
        d[:, 1:] += C[:, 1:] != C[:, :-1]
        d[:, :-1] += C[:, :-1] != C[:, 1:]
        M["cpBnd"] = pct(float(np.mean(d > 0)))
    lines = ["%% generated by tools/fractal_numbers.py -- do not edit by hand"]
    for k in sorted(M):
        lines.append("\\newcommand{\\%s}{%s}" % (k, M[k]))
    open(os.path.join(ROOT, "paper", "numbers.tex"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    missing = [k for k, v in M.items() if "??" in v]
    print("wrote paper/numbers.tex: %d macros, %d missing %s" % (len(M), len(missing), missing))


if __name__ == "__main__":
    main()
